import {
  LayoutDashboard,
  Users,
  UserX,
  MessageSquareWarning,
  CreditCard,
  BookOpen,
  FileText,
  CheckCircle,
  AlertTriangle,
  CalendarDays,
  Landmark,
  LogOut,
  GraduationCap,
  ClipboardList,
  Wallet,
  ShieldCheck,
  Clock,
} from "lucide-react";

export const sidebars = {
  admin: [
    { name: "Dashboard", link: "/admin/dashboard", icon: LayoutDashboard },
    { name: "Student Cancel Class", link: "/admin/cancel-reasons", icon: UserX },
    { name: "Teacher Suggestions List", link: "/admin/teacher-suggestions", icon: MessageSquareWarning },
    { name: "Fee Approvals", link: "/admin/fee-approvals", icon: CreditCard },
    { name: "Students Complaints", link: "/admin/complaints", icon: AlertTriangle },
    { name: "Syllabus", link: "/student/syllabus/student/syllabus", icon: BookOpen },
    { name: "Student Monthly Reports", link: "/admin/montly-reports", icon: ClipboardList },
    { name: "Teachers Salary Management", link: "/admin/teachers", icon: Wallet },
    { name: "Teacher Bank List", link: "/admin/teacher-bank-list", icon: Landmark },
    { name: "Logout", link: "#", icon: LogOut, logout: true },
    { name: "Login Student Portal", link: "/login?role=student", icon: GraduationCap },
    { name: "Login Teacher Portal", link: "/login?role=teacher", icon: Users },
  ],

  teacher: [
    { name: "Dashboard", link: "/teacher/dashboard", icon: LayoutDashboard },
    { name: "Syllabus", link: "/teacher/syllabus", icon: BookOpen },
    { name: "Student Attendance", link: "/teacher/attendance", icon: CheckCircle },
    { name: "Leave Management", link: "/teacher/teacher-leave", icon: CalendarDays },
    { name: "Salary Records", link: "/teacher/salary-record", icon: Wallet },
    { name: "View Attendance", link: "/teacher/view-attendance", icon: ClipboardList },
    { name: "Bank Details", link: "/teacher/bank-details", icon: Landmark },
    { name: "Rules & Regulation", link: "/teacher/rules", icon: ShieldCheck },
    { name: "Student Cancel Class", link: "/teacher/cancel-class", icon: Clock },
    { name: "Logout", link: "#", icon: LogOut, logout: true },
  ],

  student: [
    { name: "Dashboard", link: "/student/dashboard", icon: LayoutDashboard },
    { name: "Class Schedule", link: "/student/class-schedule", icon: CalendarDays },
    { name: "Assignments", link: "/student/assignments", icon: FileText },
    { name: "Syllabus", link: "/student/view-syllabus", icon: BookOpen },
    { name: "Rules & Regulation", link: "/student/rules", icon: ShieldCheck },
    { name: "Logout", link: "#", icon: LogOut, logout: true },
  ],
};
